
package equipocesar_sebastian.project2os;
import Estructuras.DoubleList;
import Estructuras.block;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author sebas
 */
public class JFrameP extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameP.class.getName());
    DoubleList blockList = new DoubleList();
    Color[] colours = {new Color(30,144,255),new Color(80, 200, 120), new Color(255, 191, 0), new Color(220,20,60), new Color(255,192,203)};

    /**
     * Creates new form JFrameP
     */
    public JFrameP() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rType = new javax.swing.ButtonGroup();
        PanelBG = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root");
        DefaultTreeModel treeRoot = new DefaultTreeModel(root);
        jTree1 = new javax.swing.JTree(root, true);
        jPanel1 = new javax.swing.JPanel();
        tipoPlanificacion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        AgregarArchivo = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        CantBloques = new javax.swing.JTextField();
        EliminarNodo = new javax.swing.JButton();
        ModificarNodo = new javax.swing.JButton();
        CrearCarpeta = new javax.swing.JButton();
        rAdmin = new javax.swing.JRadioButton();
        rUser = new javax.swing.JRadioButton();
        nroBloques = new javax.swing.JTextField();
        setBloques = new javax.swing.JButton();
        ColorDecidido = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        FATable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMULADOR VIRTUAL DE SISTEMA DE ARCHIVOS");
        setBounds(new java.awt.Rectangle(0, 0, 850, 600));
        setMinimumSize(new java.awt.Dimension(850, 600));
        setResizable(false);

        PanelBG.setBackground(new java.awt.Color(153, 217, 234));
        PanelBG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelBG.setForeground(new java.awt.Color(153, 217, 234));
        PanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTree1);

        PanelBG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 300, 400));

        jPanel1.setBackground(new java.awt.Color(179, 111, 237));

        tipoPlanificacion.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        tipoPlanificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "SSTF", "SCAN", "C-SCAN" }));
        tipoPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPlanificacionActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jButton1.setText("VerBloques");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AgregarArchivo.setText("Agregar");
        AgregarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarArchivoActionPerformed(evt);
            }
        });

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        CantBloques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantBloquesActionPerformed(evt);
            }
        });
        CantBloques.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantBloquesKeyTyped(evt);
            }
        });

        EliminarNodo.setText("Eliminar");
        EliminarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarNodoActionPerformed(evt);
            }
        });

        ModificarNodo.setText("Modificar");
        ModificarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarNodoActionPerformed(evt);
            }
        });

        CrearCarpeta.setText("Directorio");
        CrearCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCarpetaActionPerformed(evt);
            }
        });

        rType.add(rAdmin);
        rAdmin.setSelected(true);
        rAdmin.setText("Administrador");
        rAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAdminActionPerformed(evt);
            }
        });

        rType.add(rUser);
        rUser.setText("Usuario");
        rUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUserActionPerformed(evt);
            }
        });

        nroBloques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroBloquesActionPerformed(evt);
            }
        });
        nroBloques.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nroBloquesKeyTyped(evt);
            }
        });

        setBloques.setText("Set bloques");
        setBloques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBloquesActionPerformed(evt);
            }
        });

        ColorDecidido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Azul", "Verde", "Naranja", "Rojo", "Rosado", "" }));
        ColorDecidido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorDecididoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Cantidad de bloques");

        jLabel3.setText("Capacidad Bloques");

        jLabel4.setText("Color de bloque");

        jLabel5.setText("PLanificación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rUser)
                            .addComponent(rAdmin))
                        .addGap(8, 8, 8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setBloques)
                    .addComponent(nroBloques, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ColorDecidido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CantBloques, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(tipoPlanificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(AgregarArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminarNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarNodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrearCarpeta)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rAdmin)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoPlanificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CantBloques, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rUser)
                    .addComponent(setBloques)
                    .addComponent(ColorDecidido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroBloques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarArchivo)
                    .addComponent(EliminarNodo)
                    .addComponent(ModificarNodo)
                    .addComponent(CrearCarpeta)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        PanelBG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 770, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro", "Nombre", "Operacion", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        PanelBG.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 430, 180));

        FATable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Bloques", "Direccion", "Color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FATable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(FATable);
        if (FATable.getColumnModel().getColumnCount() > 0) {
            FATable.getColumnModel().getColumn(0).setResizable(false);
            FATable.getColumnModel().getColumn(1).setResizable(false);
            FATable.getColumnModel().getColumn(2).setResizable(false);
            FATable.getColumnModel().getColumn(3).setResizable(false);
        }

        PanelBG.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 430, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        PanelBG.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(blockList.getSize() != 0){
            JFrame newframe = new JFrame();
            newframe.setSize(400,400);
            JPanel generalPanel = new JPanel();
            int blocks = blockList.getSize();
            int rows = (int) Math.sqrt(blocks);
            generalPanel.setLayout(new GridLayout(rows,0,3,3));

            JButton[] buttons = new JButton[blocks];
            for (int i = 0; i < blocks; i++) {
                buttons[i] = new JButton(String.valueOf(i));
                buttons[i].setBackground(blockList.getBlock(i).getColor());
                buttons[i].setOpaque(true);
                buttons[i].setBorderPainted(false);
                buttons[i].setFont(new Font("Italica", Font.BOLD, 12));
                generalPanel.add(buttons[i]);
            }
            newframe.add(generalPanel);
            newframe.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese el tamano de los bloques");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUserActionPerformed
        tipoPlanificacion.setEnabled(false);
        
    }//GEN-LAST:event_rUserActionPerformed

    private void AgregarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarArchivoActionPerformed

        if(Nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe Ingresar un Nombre primero");
        }else if(blockList.getSize() == 0){
            JOptionPane.showMessageDialog(null, "Por favor Ingrese un numero de Bloques inicial");
        }else if(CantBloques.getText().equals("") || Integer.parseInt(CantBloques.getText()) <= 0 || Integer.parseInt(CantBloques.getText()) > blockList.getSize()){
            JOptionPane.showMessageDialog(null, "Por favor Ingrese un numero de Bloques de Archivo Valido (Menor a la cantidad Maxima y Mayor a 0,)");
        }else if(ColorDecidido.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione un Color");
        }else if(jTree1.getSelectionPath() == null){
            JOptionPane.showMessageDialog(null, "Por favor seleccione en el Jtree su carpeta");
        }else{
            
            block aux = this.blockList.getFirst();
            try{
                while(aux != null){
                    if(aux.isDisponible()){
                        int contador = 0;
                        block aux2 = aux;
                        for (int i = 0; i < Integer.parseInt(CantBloques.getText()); i++) {
                            if(aux2.isDisponible()){
                                contador++;
                                aux2 = aux2.getpNext();
                                System.out.println(contador);
                            }
                        }
                        if (contador == Integer.parseInt(CantBloques.getText())){
                            String initial = String.valueOf(aux.getNumero());
                            for (int i = 0; i < contador; i++) {
                                aux.setDisponible(false);
                                aux.setColor(colours[ColorDecidido.getSelectedIndex()-1]);
                                aux.setPertenencia(Nombre.getText());
                                aux = aux.getpNext();
                                ;
                            }
                            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
                            DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(Nombre.getText(), false);     
                            selectedNode.add(newNode);
                            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
                            model.reload();
                            
                            String data[] = {Nombre.getText(), CantBloques.getText(), initial, String.valueOf(ColorDecidido.getSelectedItem())};
                            DefaultTableModel tblModel = (DefaultTableModel) FATable.getModel();
                            tblModel.addRow(data);
                            
                            return;
                        }else{
                            aux = aux2;
                        }
                    }
                    aux = aux.getpNext();
                }
            }catch(NullPointerException e){
                JOptionPane.showMessageDialog(null, "No hay suficiente espacio para el Archivo");
            }
        }
        
        
    }//GEN-LAST:event_AgregarArchivoActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void rAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAdminActionPerformed
        tipoPlanificacion.setEnabled(true);
    }//GEN-LAST:event_rAdminActionPerformed

    private void CantBloquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantBloquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantBloquesActionPerformed

    private void CantBloquesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantBloquesKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_CantBloquesKeyTyped

    private void CrearCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCarpetaActionPerformed
        
        if(!rAdmin.isSelected()){
            JOptionPane.showMessageDialog(null, "Usted no es Administrador para Eliminar Archivos");
        }else if(jTree1.getSelectionPath() == null){
            JOptionPane.showMessageDialog(null, "Por favor seleccione en el Jtree su carpeta o archivo");
        }else{
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
            DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(Nombre.getText(), true);     
            selectedNode.add(newNode);
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
            model.reload();
        }        
        
        
        
    }//GEN-LAST:event_CrearCarpetaActionPerformed

    private void EliminarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarNodoActionPerformed
        if(!rAdmin.isSelected()){
            JOptionPane.showMessageDialog(null, "Usted no es Administrador para Eliminar Archivos");
        }else if(jTree1.getSelectionPath() == null){
            JOptionPane.showMessageDialog(null, "Por favor seleccione en el Jtree su carpeta o archivo");
        }else{
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
            selectedNode.removeFromParent();
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
            model.reload();
            
            block aux = blockList.getFirst();
            while(aux!=null){
                if(aux.getPertenencia().equals(selectedNode.getUserObject().toString())){
                    aux.setColor(Color.WHITE);
                    aux.setDisponible(true);
                    aux.setPertenencia("");
                }
                aux = aux.getpNext();
            }
            DefaultTableModel tbModel = (DefaultTableModel) FATable.getModel();
            for (int i = 0; i <= tbModel.getColumnCount(); i++) {
                String name = (String) tbModel.getValueAt(i, 0);
                if(name.equals(selectedNode.getUserObject().toString())){
                    tbModel.removeRow(i);
                    break;
                }
            } 
        }
    }//GEN-LAST:event_EliminarNodoActionPerformed

    private void ModificarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarNodoActionPerformed

        if(!rAdmin.isSelected()){
            JOptionPane.showMessageDialog(null, "Usted no es Administrador para Modificar Archivos");
        }else if(jTree1.getSelectionPath() == null){
            JOptionPane.showMessageDialog(null, "Por favor seleccione en el Jtree su carpeta o archivo");
        }else{
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();   
            selectedNode.setUserObject(Nombre.getText());
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
            model.reload();
        }
        
        
    }//GEN-LAST:event_ModificarNodoActionPerformed

    private void tipoPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPlanificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPlanificacionActionPerformed

    private void nroBloquesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nroBloquesKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_nroBloquesKeyTyped

    private void nroBloquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroBloquesActionPerformed

    }//GEN-LAST:event_nroBloquesActionPerformed

    private void setBloquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBloquesActionPerformed
        try{
            int nro = Integer.parseInt(nroBloques.getText());
            for (int i = 0; i < nro; i++) {
        
                block aux = new block(i);
                this.blockList.insertLast(aux);
            }
         
            nroBloques.setEnabled(false);
            setBloques.setEnabled(false);
        System.out.println(blockList.getSize());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "No puede ser Vacio el Nro de Bloques");
        }
    }//GEN-LAST:event_setBloquesActionPerformed

    private void ColorDecididoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorDecididoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorDecididoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameP().setVisible(true));

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarArchivo;
    private javax.swing.JTextField CantBloques;
    private javax.swing.JComboBox<String> ColorDecidido;
    private javax.swing.JButton CrearCarpeta;
    private javax.swing.JButton EliminarNodo;
    private javax.swing.JTable FATable;
    private javax.swing.JButton ModificarNodo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JPanel PanelBG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    javax.swing.JTree jTree1;
    private javax.swing.JTextField nroBloques;
    private javax.swing.JRadioButton rAdmin;
    private javax.swing.ButtonGroup rType;
    private javax.swing.JRadioButton rUser;
    private javax.swing.JButton setBloques;
    private javax.swing.JComboBox<String> tipoPlanificacion;
    // End of variables declaration//GEN-END:variables
}
